runners:
  - name: oracle-runner
    cloud: digitalocean
    instance_type: s-1vcpu-1gb
    machine_image: ubuntu-20-04-x64
    workflow: .github/workflows/workflow.yml
    labels:
      - oracle-cloud
